
Create Database Jaisingh;
Use Jaisingh;

CREATE TABLE EMP(
	E_NO INT,
	NAME VARCHAR(30),
	DEPT_ID INT
)

CREATE TABLE DEPT(
	DEPT_ID INT,
	DEPT_NAME VARCHAR(30)
)

INSERT INTO EMP VALUES(4578,'JAISINGH',01 )
INSERT INTO EMP VALUES(7698,'AYAAN',10 )
INSERT INTO EMP VALUES( 1268,'VATSALA',05)
INSERT INTO EMP VALUES( 1865,'AKSHARA',02)

INSERT INTO DEPT VALUES( 01,'ANALYTICS')
INSERT INTO DEPT VALUES( 05,'DATA')
INSERT INTO DEPT VALUES( 07,'LINUX')
INSERT INTO DEPT VALUES( 02,'WINDOWS')


SELECT * FROM EMP

SELECT * FROM DEPT


--INNER JOIN

SELECT E.E_NO, E.NAME, D.DEPT_NAME, E.DEPT_ID
FROM EMP E --THIS IS LEFT TABLE SINCE IT IS WRITTEN FIRST
INNER JOIN DEPT D
ON E.DEPT_ID = D.DEPT_ID;

--OUTER JOIN

SELECT * FROM EMP

SELECT * FROM DEPT

SELECT E.E_NO, E.NAME, D.DEPT_NAME, E.DEPT_ID
FROM EMP E --THIS IS LEFT TABLE SINCE IT IS WRITTEN FIRST
OUTER JOIN DEPT D
ON E.DEPT_ID = D.DEPT_ID;

--LEFT JOIN

SELECT * FROM EMP

SELECT * FROM DEPT

SELECT E.E_NO, E.NAME, D.DEPT_NAME, E.DEPT_ID
FROM EMP E --THIS IS LEFT TABLE SINCE IT IS WRITTEN FIRST
LEFT JOIN DEPT D
ON E.DEPT_ID = D.DEPT_ID;

--RIGHT JOIN

SELECT * FROM EMP

SELECT * FROM DEPT

SELECT E.E_NO, E.NAME, D.DEPT_NAME, E.DEPT_ID
FROM EMP E --THIS IS LEFT TABLE SINCE IT IS WRITTEN FIRST
RIGHT JOIN DEPT D
ON E.DEPT_ID = D.DEPT_ID;

--FULL JOIN

SELECT * FROM EMP

SELECT * FROM DEPT

SELECT E.E_NO, E.NAME, D.DEPT_NAME, E.DEPT_ID
FROM EMP E --THIS IS LEFT TABLE SINCE IT IS WRITTEN FIRST
FULL JOIN DEPT D
ON E.DEPT_ID = D.DEPT_ID;

--SELF JOIN

--WILDCARD

SELECT *
FROM EMP
WHERE NAME LIKE 'A%' --% CAN TAKE ANY LENGTH

SELECT *
FROM EMP
WHERE NAME LIKE 'A______' --UNDERSCORE HAS TO BE A SPECIFIC LENGTH

INSERT INTO EMP VALUES(5645,'ABHISHEK',16 )
INSERT INTO EMP VALUES( 1563,'ABHILASHA', 17)

SELECT *
FROM EMP
WHERE NAME LIKE 'A__I%'

--AGGREGATE FUCNTIONS 
--AGGREGATE FUNCTIONS ONLY RUN ON NUMERICAL DATA

CREATE TABLE AGG(
	RNO INT,
	NAME VARCHAR(30),
	MARKS INT
)


INSERT INTO AGG VALUES(01,'JAISINGH',100 )
INSERT INTO AGG VALUES( 02,'ROSHAN',75)
INSERT INTO AGG VALUES( 03,'AYAAN',85)
INSERT INTO AGG VALUES( 04,'AKSHARA',90)
INSERT INTO AGG VALUES( 05,'VATSALA',80)

SELECT NAME, MAX(MARKS) FROM AGG

SELECT *  FROM AGG


  



SELECT NAME ,MARKS FROM AGG ORDER BY MARKS

INSERT INTO AGG VALUES(01,'JAISINGH',75 )
INSERT INTO AGG VALUES( 02,'ROSHAN',55)
INSERT INTO AGG VALUES( 03,'AYAAN',45)
INSERT INTO AGG VALUES( 04,'AKSHARA',60)
INSERT INTO AGG VALUES( 05,'VATSALA',70)


CREATE TABLE MSC(
	SUB VARCHAR(10),
	NAME VARCHAR(30),
	MARKS INT
)


INSERT INTO MSC VALUES('ENG','JAISINGH',85 )
INSERT INTO MSC VALUES('ENG','ROSHAN',78)
INSERT INTO MSC VALUES('ENG','AYAAN',82)
INSERT INTO MSC VALUES('ENG','AKSHARA',92)
INSERT INTO MSC VALUES('ENG','VATSALA',86)
INSERT INTO MSC VALUES('HIN','JAISINGH',72 )
INSERT INTO MSC VALUES( 'HIN','ROSHAN',80)
INSERT INTO MSC VALUES( 'HIN','AYAAN',64)
INSERT INTO MSC VALUES( 'HIN','AKSHARA',89)
INSERT INTO MSC VALUES( 'HIN','VATSALA',86)
INSERT INTO MSC VALUES('MATHS','JAISINGH',95 )
INSERT INTO MSC VALUES( 'MATHS','ROSHAN',92)
INSERT INTO MSC VALUES( 'MATHS','AYAAN',83)
INSERT INTO MSC VALUES( 'MATHS','AKSHARA',77)
INSERT INTO MSC VALUES( 'MATHS','VATSALA',65)

SELECT * FROM MSC

SELECT MIN(MARKS) AS MIN_MARKS ,MAX(MARKS) AS MAX_MARKS,SUB FROM MSC GROUP BY SUB

SELECT MIN(MARKS) AS MIN_MARKS ,MAX(MARKS) AS MAX_MARKS,NAME FROM MSC GROUP BY NAME

SELECT SUM(MARKS) AS TOTAL, AVG(MARKS) AS AVG ,NAME FROM MSC GROUP BY NAME

--




######################################################################

CREATE DATABASE Ayush;


use Ayush;

create table books(
	id int primary key,
	book_name nvarchar(200),
	book_price money);


insert into books(id, book_name, book_price)
values(1, 'Into SSIS', 452),
(2, 'BDA', 785),
(3, 'ML', 563),
(4, 'Data Warehouse', 1023),
(5, 'Selenium', 4532),
(6, 'Python Basic', 165);


SELECT * into books_hist FROM books WHERE 2 =0;

SELECT *FROM books;
SELECT* FROM books_hist;

-- Adding one more entry in the books table after running SSIS

insert into books(id, book_name, book_price)
values(7, 'Data Mining', 769);

insert into books(id, book_name, book_price)
values(8, 'Statistical modelling', 956);

insert into books(id, book_name, book_price)
values(9, 'Linear models', 855);

insert into books(id, book_name, book_price)
values(5, 'ANOVA', 1023);


insert into books(id, book_name, book_price)
values(6, 'ML', 1023);

-- Updating record in books

update books
set book_price = 300
where id = 3;

update books
set book_price = 896
where id = 9;

-- Droping a particular entry from books table
delete from books where id = 5;

select * from books

-- Creating another empty table with same structure
select * into books_hist1 from books where 1=0;

###############################################################################
